export default {
  schoolLeads: [],
  franquia: [],
  clientes: [],
  clientesAngolas: [],
  fazendas: [],
  fazendasAngolas: [],
  users: [],
  usersAngolas: [],
  pragas: [],
  pragasTipo: [],
  pragasEspecie: [],
  pragasEstagio: [],
  daninhasTipo: [],
  daninhasEspecie: [],
  daninhasEstagio: [],
  doencasTipo: [],
  doencasEspecie: [],
  doencasEstagio: [],
  colors: [],
  armadilhasEstagio: [],
  armadilhasEspecie: [],
  armadilhasTipo: [],
  talhoes: []
};
